README.md
scripts/serve-dist.js

When developing on localhost, the http://localhost:5000 returns a directory view instead of the web app.
Change the `serve-handler` config will solve the issue.

fix: the local develop URL doesn't work without GitHub repo pathname

---

src/vs/github1s/util.ts

👋  I wanted to be able to be able to use this repo with Alfred's Web Search feature. The query provided to Alfred is automatically URL encoded, so simply splitting on `/` doesn't work. This is kind of a fringe use case, so no issues if you don't want to go down this road.

Support URL Encoded Forward Slash

---

extensions/github1s/src/client.ts
extensions/github1s/src/github1sfs.ts

The GraphQL query should never be executed in `readFile` function. Because the GraphQL query always reads all file content from the directory level.
Assume GraphQL is enabled, when the `readFile` is triggered, the related `readDirectory` of the file's directory must be executed already. If the file is a text file and the `File` object must have valid `data`, and the only case it has `data: null` is the file itself is binary, thus execute the query again wouldn't add any value. So we need to directly call the RESTful endpoint to get the file content.
Before this fix:
After fix:

fix: GraphQL query can't handle binary file

---

extensions/github1s/src/client.ts
extensions/github1s/src/github1sfs.ts

This PR depends on #96 
After this change, one GraphQL query will return 4 level file information.

feat: use 4 level traversal to optimize the GraphQL query times

---

resources/index-hash.html
resources/index.html
src/vs/code/browser/workbench/workbench.ts

This depends on the #101 
@conwnet do you think whether we need to change the `index-dev.html` and `index-hash.html` files?
The CSS load spinner from https://loading.io/css/. Please feel free to update it to other implementations.
You can preview on https://github1s-git-load-spinner.xcv58.vercel.app/

feat: add loading spinner for inital page

---

extensions/github1s/src/client.ts

You can test https://github1s-git-gql-too-large.xcv58.vercel.app/torvalds/linux/blob/HEAD/Documentation/x86/x86_64/boot-options.rst
It seems we have to use one level query to make the query robust:
With only one level:
With two levels:

fix: make GraphQL use one level directory query to support big repo

---

.github/workflows/deploy.yml
scripts/hash.sh

Tested on my repo, with tag:
Without tag:
Action successfully update the gh-pages branch:
https://github.com/xcv58/github1s/runs/1901269075?check_suite_focus=true
https://github.com/xcv58/github1s/runs/1901346185?check_suite_focus=true
https://github.com/xcv58/github1s/tree/gh-pages
commits history:
https://github.com/xcv58/github1s/commits/gh-pages
Sample URL:
https://xcv58.github.io/github1s/
It's broken because of the subpath.

feat: add auto deploy GitHub action based on tags

---

extensions/github1s/src/github1sfs.ts

- The provideFileSearchResults doesn't support branch name with slash(es)
- Use lazy load for search functionality & support branch switch

fix: search issue with multiple branches or slash-separated branch name

---

resources/index-dev.html
resources/index-hash.html
resources/index.html
src/vs/code/browser/workbench/workbench.ts

missing webviewEndpoint will fallback to visit 'https://{{uuid}}.vscode-webview-test.com/{{commit}}'
See: https://github.com/microsoft/vscode/blob/8cb4a6907be408d48e94428aa033bb81af4846a9/src/vs/workbench/services/environment/browser/environmentService.ts#L222

feat: set config.webviewEndpoint

---

src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts

Preview link: https://github1s-git-fix-open-folder.xcv58.vercel.app/xcv58/github1s/tree/index/html/test/src/vs
The failed reason is here: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/common/explorerModel.ts#L367
```js
equalsIgnoreCase(this.resource.authority, resource.authority)
```
`this.resource.authority` would be `''` and `resource.authority` will be the actual one if we set it. If we set it, the comparison would be false thus it stops revealing the directory.

fix: couldn't focus corresponding directory from URL

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md

add .devcontainer files to allow VSCode to use Docker for the develoment environment

add .devcontainer files to allow VSCode to use Docker for the Dev Env

---

src/vs/github1s/notification.ts

"I know" appears to imply that the user already knew the information before reading the notification.
Besides, since the text of the notification is customizable, it makes sense to use a more generic confirmation text.

Make banner confirmation button text more generic

---

package.json
scripts/watch.sh
yarn.lock

The `yarn watch 2>&1 > /dev/null` will eat all possible build errors and fail silently. This PR breaks the `watch.sh` to smaller task and uses the `npm-run-all` to run tasks in parallel and expose potential errors to shell output.

fix: update the `yarn watch` command to expose potential build errors

---

extensions/github1s/src/api.ts
extensions/github1s/src/commands.ts
extensions/github1s/src/util/git-ref.ts
extensions/github1s/src/util/index.ts

the [List Branches](https://docs.github.com/en/rest/reference/repos#list-branches) API only returned max to 100 branches for per request, we will fetch max to 2 request, so only no more than 200 branches are supported before
[List matching references](https://docs.github.com/en/rest/reference/git#list-matching-references) can returned all branches/tags for a request
and there is an issue for this API https://github.com/github/docs/issues/3863

feat: replace `List Branches` API with `List matching references` API

---

README.md

Update Bookmarklet in README. Make the URL recoverable to github.com.

Update README Bookmarklet

---

src/vs/workbench/browser/web.main.ts

the vscode distinguish different workspaces use `workspace.folderUri.toString()` for `Single-folder workspace`:
https://github.com/microsoft/vscode/blob/1.52.1/src/vs/workbench/browser/web.main.ts#L367
Current for all repos, our `folderUri` always is `{ scheme: 'github1s', authority: '', path: '/' }`, it causes a bug when we switch multi repositories in browser.
This bug can be repeated like this:
1. Visit `https://github1s.com/microsoft/vscode`, open some files random. Then refresh our browser, we can see it will restore the files previous opening.
2. Visit `https://github1s.com/facebook/react`, then we can see, this pagesite want to restore `previous files`, but it belong to `microsoft/vscode`, so we get errors in devtools and this editors close immediately.
How to fix it:
Change the …

feat: state isolation between different repository

---

.gitpod.Dockerfile
.gitpod.yml
README.md
extensions/svelte-web/package.json

This PR introduces a ready-to-code development environment on [Gitpod](https://www.gitpod.io). With a single click, a new development environment with all prerequisites installed and `yarn && yarn build` already executed starts up.
The "Development" chapter in the `README` provides the link to start the dev environment.
To get the full benefits, please enable the [Gitpod GitHub App](https://github.com/apps/gitpod-io). This enables automated [prebuilds](https://www.gitpod.io/docs/prebuilds) for all branches and PRs.

Configure Gitpod online dev environment

---

.github/workflows/build.yml

It seems the GitHub Actions' macOS environment is unstable. Try to remove the timeout restriction and bump the node setup version.
If it still fails randomly, we should disable macOS on CI. 
-------
Failed jobs:
https://github.com/xcv58/github1s/runs/2096965487?check_suite_focus=true
https://github.com/conwnet/github1s/runs/2097192100?check_suite_focus=true
Success jobs:
https://github.com/xcv58/github1s/actions/runs/646879291
https://github.com/xcv58/github1s/actions/runs/646754214
And above commits are almost identical with just metadata change in the yml file.
The macOS job randomly failed on `yarn install`.
We should remove macOS for now to have a reliable CI for other PRs and investigate how to onboard macOS late.

Fix CI failure

---

README.md

Repositree a browser extension that helps to explore GitHub Repository.

repositree added

---

extensions/github1s/src/interfaces/github-api-rest.ts
extensions/github1s/src/listeners/router/source-control.ts
extensions/github1s/src/listeners/vscode.ts
extensions/github1s/src/repository.ts
extensions/github1s/src/router/parser/commit.ts
extensions/github1s/src/router/parser/index.ts
extensions/github1s/src/source-control/changes.ts

Support the url looks like `https://github.com/conwnet/github1s/commit/39f10618df450771389d01bc88d117deaf79eedf`
#236

feat: support github commit

---

extensions/github1s/src/helpers/async.ts
extensions/github1s/src/listeners/router/explorer.ts
extensions/github1s/src/providers/fileSearchProvider.ts
extensions/github1s/src/router/index.ts

Now, if the user open a repository in GitHub1s, it will only fetch the first level files. (In order to display the content faster)
And when the user press `Ctrl/Command + P`, it will use the `recursive=true` param of `get-a-tree` API to fetch all files, then populate the files into the fileSystemProvider's cache:
https://github.com/conwnet/github1s/blob/e079f7a8f6d0e94347b1e61f82b8e009f87d8737/extensions/github1s/src/providers/fileSearchProvider.ts#L60
So if we haven't ever press the `Ctrl/Commond + P`, we need make a `get-a-tree` request **every time** you open a new folder, which is **slow and  waste**.
I think we can fetch the full files tree sliently after the page loaded. Although it may waste a request, but it's will not to create a new request when the user opens another folder. …

feat: preload fuze and full files tree

---

extensions/github1s/package.json
extensions/github1s/src/commands/index.ts
extensions/github1s/src/commands/pull.ts
extensions/github1s/src/helpers/util.ts
extensions/github1s/src/listeners/router/explorer.ts
extensions/github1s/src/listeners/vscode.ts
extensions/github1s/src/providers/changedFileDecorationProvider.ts
extensions/github1s/src/providers/index.ts
extensions/github1s/src/providers/sourceControlDecorationProvider.ts
extensions/github1s/src/repository.ts
extensions/github1s/src/source-control/changes.ts
extensions/github1s/src/views/pull-list-view.ts
extensions/github1s/yarn.lock

Improve the user experience of Pull Request View, support for quicking view change files

feat: support for quicking view change files in pull request view

---

extensions/github1s/src/extension.ts
extensions/github1s/src/listeners/router/explorer.ts
extensions/github1s/src/listeners/vscode.ts
extensions/github1s/src/router/parser/commits.ts
extensions/github1s/src/router/parser/index.ts

Bug: editor will close when open it at first time
Steps of recurrence:
1. Open https://github1s.com
2. Open any file, the editor will force closed at the first time
This is because we refresh the explorer state when the pageType changed. In fact the refresh action should not be occured when the pageType is become BLOB from TREE, vice versa. Sorry for my mistake.
https://github.com/conwnet/github1s/blob/bbc88fee5307a48128be0753f481c1b21a549b9b/extensions/github1s/src/listeners/router/explorer.ts#L19-L24
Another things is add the `commits` route support for GitHub.

fix: editor will close when open it at first time & add commits route support

---

extensions/github1s/src/helpers/fetch.ts

Now we use the `cache: 'force-cache'` as the default fetch cache option, which will break the data updating.
Steps to Reproduce:
1. Someone open `github1s.com` without login and met a RateLimit Error.
2. Provider an OAuth token Manual.
3. The user stil can't get the correct response.

fix: can not update data because of the fetch cache

---

extensions/github1s/src/listeners/vscode.ts

It is a bug:
Steps to Reproduce:
1. Open any request for example `https://github1s.com/conwnet/github1s/pull/265`
2. Switch to `Source Control Panel`
3. Open any file and close it (close all editors)
4. The url would changed to ~~`https://github1s.com/conwnet/github1s`~~ `https://github1s.com/conwnet/github1s/tree/17ba76f2293bc3db05c90174be0205d679703311` (it is wrong)
I am really sorry for that...🙏

fix: the browser url changed in a wrong way

---

extensions/github1s/src/router/parser/tree.ts

1. when user visit the url looks like `https://github1s.com/:owner/:repo/tree/:ref` and no other string after this, we can just assume the ref is `:ref`, fetch all branches/tags is not necessary.
2. `await` make the `getBranches` and `getTags` serially, we can use `Promise.all` to make it in parallel

perf: optimizing the ref matching logic

---

.prettierignore
package.json
vscode-web-github1s/extensions/typescript-language-features/src/typescriptServiceClient.ts
vscode-web-github1s/package.json
vscode-web-github1s/scripts/sync-code.sh
yarn.lock

Related https://github.com/microsoft/vscode/issues/125278
All changed codes:
https://github.com/conwnet/github1s/pull/328/files#diff-7dcf414450b146f7aefa89c23af7b78b94ac1cc90a9c6ff6bed37c33a9ce03ebR696-R698
This change has merged into vscode, and it will be removed when we upgrade to newer version vscode.

fix: can not found typescript basic symbol definitions

---

api/vscode-unpkg/index.js
api/vscode-unpkg/yarn.lock
scripts/serve-dist.js

Current vscode-unpkg proxy miss some necessary http headers, such like `content-type`, `cache-control`.
This will cause the images resource from vscode-unpkg can not display.

fix: vscode-unpkg proxy miss necessary headers

---

extensions/github1s/src/helpers/func.ts

`wait: number` is unused, and instead the timeout ID is passed to `setTimeout`. I guess this wasn't intentional.

Fix debounce time

---

scripts/serve-dist.js

In some cases the proxy exits because `res` is undefined:
```
/Users/zhb/Projects/ByteLegend/github1s/scripts/serve-dist.js:18
res.writeHead(500, {
^
ReferenceError: res is not defined
at ProxyServer.handleProxyError (/Users/zhb/Projects/ByteLegend/github1s/scripts/serve-dist.js:18:2)
at ProxyServer.emit (/Users/zhb/Projects/ByteLegend/github1s/node_modules/eventemitter3/index.js:210:27)
at ClientRequest.proxyError (/Users/zhb/Projects/ByteLegend/github1s/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)
at ClientRequest.emit (events.js:400:28)
at TLSSocket.socketCloseListener (_http_client.js:449:11)
at TLSSocket.emit (events.js:412:35)
at net.js:686:12
at TCP.done (_tls_wrap.js:564:7)
error Command failed with exit code 1.
```

Trace error before writing to response

---

vscode-web-github1s/scripts/copy-extensions.sh

Previously the script only check if `extensions/emmet/dist/browser`
exists, and skip compiling if so. This PR adds an extra `git diff`
check, and run compiling if there's any changes in `extensions`.

Fix up-to-date check issue in copy-extensions.sh

---

vscode-web-github1s/scripts/copy-extensions.sh

The fix in https://github.com/conwnet/github1s/pull/376 was not complete - because of `set -e` in `copy-extensions.sh`, the script will exit immediately when `git diff --exit-code --name-only extensions` returns non-zero. Fixed by using `||` to capture the exit code.
Verified locally.

Fix copy extensions

---

extensions/github1s/src/adapters/github1s/parse-path.ts
extensions/github1s/src/adapters/types.ts
extensions/github1s/src/extension.ts

This PR resolves #428 
Supoort for **Search** Page Type, which corresponds to the GitHub's Repo Search Page. (https://github.com/conwnet/github1s/search?q=test)
For a preview: https://github1s-git-search-page-type-vscode-github1s.vercel.app/conwnet/github1s/search?q=test

feat: add search page type

---

README.md

Replaces the image from `starchart.cc` (which is [not working anymore](https://starchart.cc/conwnet/github1)) with an image from `star-history.com`.
You can preview it [here](https://github.com/conwnet/github1s/blob/e6f610b34bb117fd6c29b80551965b2b473e6985/README.md#stargazers-over-time):

Update the "Stargazers over time" section, to get the chart displayed again

---

extensions/github1s/src/adapters/ossinsight/templates.ts

add links to jump to github directly on trending pages.
(Notice: preview domains may not work now because of oss insight api's new cors rules)

feat: add github link to trending page

---

extensions/github1s/src/adapters/github1s/parse-path.ts
extensions/github1s/src/changes/index.ts
extensions/github1s/src/changes/quick-diff.ts

make [quick diff](https://code.visualstudio.com/api/extension-guides/scm-provider#quick-diff) work in commit/pull request pages.

fix: quick diff  in commit/codereview pages

---

extensions/github1s/assets/pages/github1s-settings.js
extensions/github1s/assets/pages/gitlab1s-authentication.js
extensions/github1s/extension.webpack.config.js
extensions/github1s/package.json
extensions/github1s/src/adapters/gitlab1s/authentication.ts
extensions/github1s/src/adapters/gitlab1s/data-source.ts
extensions/github1s/src/adapters/gitlab1s/fetcher.ts
extensions/github1s/src/adapters/gitlab1s/gitlab-request.ts
extensions/github1s/src/adapters/gitlab1s/graphql.ts
extensions/github1s/src/adapters/gitlab1s/index.ts
extensions/github1s/src/adapters/gitlab1s/parse-path.ts
extensions/github1s/src/adapters/gitlab1s/router-parser.ts
extensions/github1s/src/adapters/gitlab1s/settings.ts
extensions/github1s/src/adapters/gitlab1s/token.ts
extensions/github1s/src/adapters/sourcegraph/data-source.ts
extensions/github1s/src/adapters/types.ts
extensions/github1s/src/changes/files.ts
extensions/github1s/src/global.d.ts
resources/initialize.js
webpack.config.js

- Add support for personal repo.
- Add environment variables to support custom settings.
> - `GITLAB_DOMAIN` gitlab domain, default is `https://gitlab.com`
> - `GITLAB_CREATE_TOKEN_URL` gitlab authorization url, default is `/-/profile/personal_access_tokens`

feat: support gitlab personal repo

---

extensions/github1s/assets/pages/components.css

use `--vscode-input-border` for border
> ![image](https://github.com/conwnet/github1s/assets/2452450/03a81677-29a0-4a25-bf26-f657252d063f)

fix: border styles for input on authorization page

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
package.json
yarn.lock

Using the devcontainers approach mentioned in the README did not work on my Apple Silicon Mac. To fix it, I updated the devcontainer image to use a newer node version, and updated the version of emsdk. Both now support the `arm64` architecture.

Update devcontainers version to Node 20

---

extensions/github1s/src/adapters/ossinsight/constants.ts
extensions/github1s/src/adapters/ossinsight/interfaces.ts
extensions/github1s/src/adapters/ossinsight/templates.ts

Migrate the OSSInsight API to public endpoint
