README.md

Add option for bookmarklet, which unlike chrome extensions will work in any browser

Bookmarklet

---

docs/guide.md

I found a typo in the doc, but it's just one word. 😅

Fix document typo

---

extensions/github1s/package.json
extensions/github1s/src/api.ts
extensions/github1s/src/client.ts
extensions/github1s/src/github1sfs.ts
extensions/github1s/src/util/context.ts
extensions/github1s/src/util/fetch.ts
extensions/github1s/src/util/index.ts
extensions/github1s/yarn.lock
extensions/scala-web/package.json

- Add GitHub GraphQL API
- Use GraphQL API to retrieve both directory and file data
- Use RESTful endpoint as a fallback if there is no token
It still needs refactors to make future development workflow easier, we can discuss the refactor plan in #12

feat: add GitHub GraphQL API

---

docs/guide.md

Inspired by https://github.com/conwnet/github1s/pull/84

Fix more grammar errors and typos in guide.md

---

src/vs/code/browser/workbench/workbench.ts
src/vs/github1s/notification.css
src/vs/github1s/notification.ts

According #51, It seems there are some users get confused with GitHub1s, maybe we should add a notification to explain it? Please help me to review the notification message. Is it clear enough? Is there any grammatical error?😂

feat: add notification

---

extensions/github1s/src/github1sfs.ts

graph_sql has some problems now, disable it temporary #90

feat: disable graph_ql temporary

---

README.md

I just got my extension approved on firefox addons directory, i want to share it with the community

Add firefox addon to README.md

---

resources/index-dev.html
resources/index-hash.html
resources/index.html

If disable JavaScript in the browser
without this change:
with this change:

fix: add noscript tag to remind users with JS disabled

---

scripts/watch.sh

Did I miss an OCD joke in there?

Fix typo in watch.sh

---

README.md

fixed some typos and grammar, brushed the style a bit

some copyedits in README.md

---

README.md

- I've added a high-quality Demo Gif with zoom-in & zoom-out effects for URL
- Gif is fully optimized and compressed
- For better readme demonstration

Added Demo Gif

---

README.md
extensions/github1s/package.json
extensions/github1s/src/api.ts
extensions/github1s/src/github1sfs.ts
extensions/github1s/src/vscode.proposed.d.ts
extensions/github1s/yarn.lock

ctrl/command + p for fuzzy file search support

feat: fuzzy file search support #40

---

README.md

Hi,
I added my Chrome extension into the project README. Appreciate if you can merge it.
Thank you.

Added a Chrome extension

---

README.md

I am very grateful for this project. I also created a Chrome Extension to launch github1s with a shortcut key `Ctrl(Win)/Command(Mac)+Shift+1`  so that more people can use it conveniently.
https://chrome.google.com/webstore/detail/shortcut-to-github1s/gfcdbodapcbfckbfpmgeldfkkgjknceo
The source code of my Chrome Extension is also available on GitHub, just like github1s.
https://github.com/katsuhisa91/github1s-shortcut
I've added a link to README.md. I'd be happy to merge it if you want.
Thanks!

Added a my Chrome Extension URL

---

README.md

Hi,
Cool project 👍 
I added a link to the project README with a tampermonkey script I developped.
The script adds a `Open with VSCode` button to Github repositories pages:
Thanks ;)
Regards,

📝 Update README.md with Tampermonkey scripts

---

README.md

https://github.com/conwnet/github1s/projects/1

docs: add roadmap

---

src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts

- Correct some HTML syntax (unclosed tags and attributes)
- Correct indentation within `escape()` calls
- Adjust capitalization in Authentication section
- Fix a typo: "will resets" → "will reset"

Fix some issues in welcome page

---

extensions/github1s/src/github1sfs.ts
extensions/github1s/src/util/index.ts
extensions/github1s/src/util/submodule.ts

feat: github submodules support #143

---

src/vs/workbench/contrib/webview/browser/pre/main.js

press cmd/ctrl+p (fuzzy search) in extensions webview would open print dialog now, disable it on `src/vs/workbench/contrib/webview/browser/pre/main.js`

feat: preventDefalt when press cmd/ctrl+p #49

---

README.md

According to https://github.com/conwnet/github1s/issues/13#issuecomment-784785795
I think there are community would be convenient

docs: add feedback block (issue add gitter link)

---

extensions/github1s/src/api.ts
extensions/github1s/src/util/index.ts

fix: can not expand folders containing a hash/pound sign/number sign/octothorpe #170

---

resources/index-hash.html
resources/index.html
src/vs/code/browser/workbench/workbench.ts
src/vs/workbench/browser/web.main.ts
src/vs/workbench/services/themes/browser/workbenchThemeService.ts

The default theme is `dark+`, but there is a light+ theme flashed in first start time, this commit will fixed it.
And The loading background is white color, change it to dark maybe more smoothful.

feat: change the loading and default theme

---

src/vs/platform/telemetry/common/telemetryService.ts

feat: disable telemetry by default

---

.github/workflows/main.yml

This bot will be really helpful to motivate newbies. Contributors will be greeted with a message whenever they:-
1. Create their first pull request
2. Create their first issue
3. get first PR merged.
related to issue #195

Added greeting bot🤖

---

extensions/github1s/src/helpers/fetch.ts
extensions/github1s/src/helpers/func.ts
extensions/github1s/src/helpers/git-ref.ts
extensions/github1s/src/providers/fileSearchProvider.ts
extensions/github1s/src/providers/fileSystemProvider/index.ts

it keeps functions arguments and its return type.
and convert some promise function into async function

refactor: better type annotations

---

.github/workflows/build.yml

Add CI support for macOS

---

README.md

docs: fix the sourcegraph link

---

extensions/github1s/src/interfaces/github-api-rest.ts
extensions/github1s/src/listeners/router/explorer.ts
extensions/github1s/src/providers/changedFileDecorationProvider.ts
extensions/github1s/src/providers/index.ts
extensions/github1s/src/providers/submoduleDecorationProvider.ts

https://beta.github1s.com/conwnet/github1s/pull/230

fix: fileDecoration not updated after switch ref

---

extensions/github1s/package.json
extensions/github1s/src/commands/gitpod.ts
extensions/github1s/src/commands/index.ts
extensions/github1s/src/commands/pull.ts
extensions/github1s/src/commands/ref.ts
extensions/github1s/src/commands/token.ts
extensions/github1s/src/extension.ts
extensions/github1s/src/helpers/date.ts
extensions/github1s/src/interfaces/github-api-rest.ts
extensions/github1s/src/repository.ts
extensions/github1s/src/router/index.ts
extensions/github1s/src/router/parser/index.ts
extensions/github1s/src/router/parser/pulls.ts
extensions/github1s/src/views/index.ts
extensions/github1s/src/views/pull-list-view.ts
extensions/github1s/src/views/settings-view.ts
extensions/github1s/yarn.lock

feat: support for pull request list

---

extensions/github1s/package.json
extensions/github1s/src/listeners/router/explorer.ts
extensions/github1s/src/providers/fileSearchProvider.ts
extensions/github1s/yarn.lock

The documatation: https://fusejs.io/api/options.html#threshold
Now visit: https://github1s.com/conwnet/github1s
Press `Ctrl/Command + P` and input `fileSystind` will match nothing, but it should matched `extensions/github1s/src/providers/fileSystemProvider/index.ts`
This PR fixed it.

feat: change the threshold in fuse options

---

extensions/github1s/src/providers/changedFileDecorationProvider.ts
extensions/github1s/src/source-control/changes.ts
extensions/github1s/src/source-control/quickDiffProviders.ts

https://code.visualstudio.com/api/extension-guides/scm-provider#quick-diff

feat: add quick diff provider for changed files and fix the decoration

---

extensions/github1s/package.json
extensions/github1s/src/commands/commit.ts
extensions/github1s/src/commands/index.ts
extensions/github1s/src/commands/pull.ts
extensions/github1s/src/interfaces/github-api-rest.ts
extensions/github1s/src/listeners/router/explorer.ts
extensions/github1s/src/listeners/router/source-control.ts
extensions/github1s/src/providers/sourceControlDecorationProvider.ts
extensions/github1s/src/repository.ts
extensions/github1s/src/views/commit-list-view.ts
extensions/github1s/src/views/index.ts
extensions/github1s/src/views/pull-list-view.ts

1. Support view/switch commits in source control panel.
2. Add **Refresh** button to `pull list view` and `commit list view`

feat: add commit list view in source control

---

extensions/github1s/package.json
extensions/github1s/src/commands/editor.ts
extensions/github1s/src/commands/index.ts
extensions/github1s/src/listeners/vscode.ts
extensions/github1s/src/source-control/changes.ts

feat: add open changes button to editor title

---

README.md

You can preview the change here: https://github.com/xcv58/github1s/tree/starchart#stargazers-over-time

Add Stargazers

---

extensions/github1s/src/commands/commit.ts
extensions/github1s/src/commands/editor.ts
extensions/github1s/src/commands/index.ts
extensions/github1s/src/commands/pull.ts
extensions/github1s/src/interfaces/github-api-rest.ts
extensions/github1s/src/providers/changedFileDecorationProvider.ts
extensions/github1s/src/repository/github-commit-manager.ts
extensions/github1s/src/repository/github-pull-manager.ts
extensions/github1s/src/repository/index.ts
extensions/github1s/src/repository/types.ts
extensions/github1s/src/router/parser/pull.ts
extensions/github1s/src/source-control/changes.ts
extensions/github1s/src/source-control/quickDiffProviders.ts
extensions/github1s/src/views/commit-list-view.ts
extensions/github1s/src/views/pull-list-view.ts

Support for loading more PRs/Commits #255

feat: support for loading for pull requets/commits

---

extensions/github1s/package.json
extensions/github1s/src/commands/global.ts
extensions/github1s/src/commands/index.ts

add the command described in #288

feat: add open on github command

---

api/github-auth-callback/index.js
extensions/github1s/src/commands/index.ts
extensions/github1s/src/commands/token.ts
extensions/github1s/src/helpers/fetch.ts
extensions/github1s/src/interfaces/github-api-rest.ts
package.json
vscode-web-github1s/package.json
vscode-web-github1s/src/vs/code/browser/workbench/workbench.ts
vscode-web-github1s/src/vs/github1s/authorizing-github.ts
vscode-web-github1s/src/vs/github1s/authorizing-overlay.css
vscode-web-github1s/src/vs/github1s/authorizing-overlay.ts
vscode-web-github1s/src/vs/github1s/util.ts
vscode-web-github1s/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
yarn.lock

1. Open a authorizing dialog for token request if the rate limit exceeted
2. If the browser block opening window, open the authorizing dialog and try again

feat: open a authorizing dialog for token request if the rate limit exceeted

---

extensions/github1s/src/helpers/fetch.ts
package.json
tests/__tests__/index.test.ts
vscode-web-github1s/package.json
vscode-web-github1s/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
vscode-web-github1s/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
yarn.lock

1. fix https://github.com/conwnet/github1s/issues/288#issuecomment-832838341
2. open settings view if current token is invalid
3. hange the update-token action to open authorizing overlay in welcome-page

feature: user experience with oauth-login

---

api/static-fallback/index.js
vercel.json

fix: 404 response is cached when static files not found

---

README.md

Safari Extension

---

extensions/github1s/src/helpers/urls.ts
extensions/github1s/src/interfaces/sourcegraph/definition.ts
extensions/github1s/src/interfaces/sourcegraph/hover.ts
extensions/github1s/src/messages.ts
extensions/github1s/src/providers/hoverProvider.ts
extensions/github1s/src/providers/index.ts

show symbol hover information from sourcegraph api

feat: support for symbol hover information

---

extensions/github1s/src/extension.ts
extensions/github1s/src/helpers/func.ts
extensions/github1s/src/listeners/vscode.ts
extensions/github1s/src/router/parser/blob.ts
extensions/github1s/src/router/types.ts

feat: support line anchors in url

---

README.md

Hey, I created a chrome extension for Github1s to open it using shortcut or the extension's popup. I didn't know there are already many extensions, so, I've added mine in this readme. It's open source as well.

Added my Chrome extension repo's link for Github1s

---

extensions/github1s/src/adapters/sourcegraph/data-source.ts
resources/initialize.js

1. fix: can not change github file encoding #401

release 0.7.2

---

extensions/github1s/src/extension.ts
extensions/github1s/src/listeners/vscode.ts
extensions/github1s/src/router/index.ts

Steps to Reproduce:
1. open https://github1s.com/conwnet/github1s/blob/HEAD/package.json#L10-L20
2. open https://github1s.com/conwnet/github1s/blob/HEAD/package.json#L20-L30 in other tab
The line number L20-30 will be cleard in the second link. (recovery to L10-L20)
After fixes:
1. open https://github1s-git-fix-selection-vscode-github1s.vercel.app/conwnet/github1s/blob/HEAD/package.json#L10-L20
2. open https://github1s-git-fix-selection-vscode-github1s.vercel.app/conwnet/github1s/blob/HEAD/package.json#L20-L30

fix: the selection of the opening file in url may be cleared

---

README.md

Hi! I made a chrome extension for GitHub1s. It allows you to reach GitHub1s with one click. I want to share it with you here. 🤗

Add my GitHub1s extension link

---

extensions/github1s/package.json
extensions/github1s/src/commands/global.ts
extensions/github1s/src/extension.ts
extensions/github1s/src/helpers/context.ts
extensions/github1s/src/router/index.ts
resources/initialize.js

click windowIndicator to open recent repositories

feat: open recent repositoies

---

extensions/github1s/src/adapters/sourcegraph/data-source.ts
extensions/github1s/src/adapters/sourcegraph/file.ts

https://github.com/sourcegraph/sourcegraph/pull/58320

fix: adapt sourcegraph api & typo

---

extensions/github1s/assets/pages/components.js
extensions/github1s/assets/pages/github1s-settings.css
extensions/github1s/assets/pages/github1s-settings.js
extensions/github1s/package.json
extensions/github1s/src/adapters/github1s/data-source.ts
extensions/github1s/src/adapters/github1s/fetcher.ts
extensions/github1s/src/adapters/github1s/index.ts
extensions/github1s/src/adapters/github1s/parse-path.ts
extensions/github1s/src/adapters/github1s/settings.ts
extensions/github1s/src/adapters/gitlab1s/data-source.ts
extensions/github1s/src/adapters/gitlab1s/fetcher.ts
extensions/github1s/src/adapters/gitlab1s/index.ts
extensions/github1s/src/adapters/gitlab1s/parse-path.ts
extensions/github1s/src/adapters/sourcegraph/data-source.ts

1. gitlab merge_requests page
2. prompt for authentication when unable to access the repository
3. add command to sync sourcegraph repo data

fix: gitlab merge_requests page & sync sourcegraph repo

---

README.md

Remove vercel from sponsors list

---

README.md

Context: https://x.com/Siddhant_K_code/status/1801447290076545099

chore: remove vercel from sponsors list

---

.github/workflows/test-wtih-vscode-build.yml
package-lock.json
package.json
scripts/build.js
scripts/link.js
scripts/postinstall.js
scripts/utils.js
src/global.d.ts
src/index.ts
vscode-web/index.html
vscode-web/package-lock.json
vscode-web/package.json
vscode-web/scripts/build/nls.js
vscode-web/scripts/build/vscode.js
vscode-web/scripts/clone.js
vscode-web/scripts/utils.js
vscode-web/scripts/watch/extensions.js
vscode-web/scripts/watch/vscode.js
webpack.config.js

This PR resolves #545 
Currently, the display language will not be automatically detect based on the user's browser; it will only take effect when the user manually switches it.
How to:
Command/Ctrl + Shift + P -> Configure Display Language
Current supported language: See [microsoft/vscode-loc](https://github.com/microsoft/vscode-loc)

feat: support multiple languages
